apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kirangothe/sprboot-mongo-moviesapi:latest
          ports:
            - containerPort: 8095
          env:
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: host
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: port
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: database

---
apiVersion: v1
kind: Service
metadata:
  name: moviesapi-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP

